#!/bin/bash

case $1 in
init)
	mkdir ./.$2/
	echo 0 > ./.$2/version
	cp ./$2 ./.$2/last_file
	cp ./$2 ./.$2/start_file
	diff --unified ./.$2/last_file ./$2 > ./.$2/diff.0
	;;
commit)
	diff --unified ./$2 ./.$2/last_file > /dev/null
	if [ $? -ne "0" ] 
	then
		read v < ./.$2/version	
		let v++
		diff --unified ./.$2/last_file ./$2 > ./.$2/diff.$v
		echo $v > ./.$2/version
		patch ./.$2/last_file ./.$2/diff.$v
	fi
	;;
status)
	diff --unified ./.$2/last_file ./$2 > /dev/null
	if [ $? -eq "0" ]
	then
		echo "0"
	else
		echo "1"
	fi
	;;
diff)
	diff --unified ./.$2/last_file ./$2
	;;
update)
	read v < ./.$2/version
	cp ./.$2/last_file ./$2
	while [ $3 -lt $v ]
	do
		patch ./$2 ./.$2/diff.$v
		let v--
	done

esac
